name: Wake Up Portfolio Projects

on:
  schedule:
    # Runs every 14 minutes, Monday to Friday, from 07:00 to 17:59 UTC
    # (This corresponds to 08:00 - 18:59 Italian time)
    - cron: '*/14 7-18 * * 1-5'
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

jobs:
  ping-backends:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Project e-commerce Backend
        run: curl -I https://e-commerce-d8be.onrender.com || true

      - name: Ping Project Talkmate Backend
        run: curl -I https://talk-mate-r68v.onrender.com || true